language: minimal
services: docker

env:
  - DOCKER_COMPOSE_VERSION=1.21.1

branches:
  only:
    - master

install:
  # Install Docker Compose
  - curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o "$HOME/bin/docker-compose"
  - chmod +x "$HOME/bin/docker-compose"
  - docker-compose --version
  
script:
  - docker-compose up -d
  - sleep 5
  - docker-compose ps
  - docker-compose logs
  #- docker-compose down -v
  - docker ps | grep -q watchtower
  
after_script:
  - docker-compose stop
  - docker-compose rm -f
